### ISSUE TITLE
FileNotFoundError and ValueError When Running test.py

### ISSUE THREAD

**Issue by SW-DeepRohit** [YZY-stack/DF40#26]
I'm encountering an error while running the following command:

python training/test.py --detector_path training/config/detector/xception.yaml --weights_path training/df40_weights/train_on_fs_matrix/simswap_ff.pth --test_dataset blendface_ff

Error Traceback:

[Errno 2] No such file or directory: '/DeepfakeBench_DF40/preprocessing/dataset_json\\blendface_ff.json'
Traceback (most recent call last):
  File "F:\DF40\DeepfakeBench_DF40\training\dataset\abstract_dataset.py", line 159, in collect_img_and_label_for_one_dataset
    with open(os.path.join(self.config['dataset_json_folder'], dataset_name + '.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/DeepfakeBench_DF40/preprocessing/dataset_json\\blendface_ff.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "training/test.py", line 212, in <module>
    main()
  File "training/test.py", line 177, in main
    test_data_loaders = prepare_testing_data(config)
  File "training/test.py", line 80, in prepare_testing_data
    test_data_loaders[one_test_name] = get_test_data_loader(config, one_test_name)
  File "training/test.py", line 63, in get_test_data_loader
    test_set = DeepfakeAbstractBaseDataset(
  File "F:\DF40\DeepfakeBench_DF40\training\dataset\abstract_dataset.py", line 94, in __init__
    image_list, label_list, name_list = self.collect_img_and_label_for_one_dataset(one_data)
  File "F:\DF40\DeepfakeBench_DF40\training\dataset\abstract_dataset.py", line 163, in collect_img_and_label_for_one_dataset
    raise ValueError(f'dataset {dataset_name} not exist!')
ValueError: dataset blendface_ff not exist!

Issue Summary:

    The script is unable to find the blendface_ff.json file in the preprocessing/dataset_json directory, causing the FileNotFoundError.
    This is followed by a ValueError, indicating that the dataset blendface_ff does not exist.

Troubleshooting Steps Taken:

    I have verified that the blendface_ff.json file is indeed present in the expected folder (/DeepfakeBench_DF40/preprocessing/dataset_json).
    I have checked the directory structure, and the file is in the correct location, but the error still persists.

Suggestions:

    Could you please help me understand why this file is not being recognized even though it is in the correct folder?
    Is there any issue with the path handling or folder structure that could cause this problem?
    Any guidance on how to resolve this would be appreciated.
    
Additional Suggestion:
   It would be helpful to improve the README file for better installation guidance and understanding of the project setup. Clear 
   instructions on directory structure, expected file locations, and any dependencies or prerequisites (such as specific dataset files) 
   would make it easier to set up and avoid these types of errors.

**Comment by Kuznetspa** [comment]
I get the same error. @YZY-stack could you help pls?

**Comment by YZY-stack** [comment]
Thanks for the question. It seems that the JSON files are not downloaded.

In our framework, we use JSON files to record all image paths. For instance, all image paths of the e4e_ff dataset are within the e4e_ff.json file. We provide a Google link for all JSON files ([link](https://drive.google.com/drive/folders/19VhAL4aDJOKvhl9stEq_ymFeHiXo6_j-?usp=drive_link))

For more details, please take a look at the image I've included below. Thanks very much for your interest.

<img width="917" alt="Image" src="https://github.com/user-attachments/assets/476e34d1-8247-442d-97cf-125ef50b91e0" />

**Comment by Kuznetspa** [comment]
Sorry, I had a different error.
I've downloaded all JSON's and put them to the `./preprocessing` folder. Also I've downloaded and extracted datasets. And I have the error, but there is this file:

<img width="722" alt="Image" src="https://github.com/user-attachments/assets/b837da1c-98c5-437a-87bd-23827129265d" />

Should I create a new issue?

**Comment by YZY-stack** [comment]
Hi @Kuznetspa, it seems like this is a new issue. However, I still appreciate your question!

I have re-downloaded the `deepfacelab.zip` and checked the `0021_0022/042.png` file. I did not find any errors with it, and the image file does exist.

However, there is one possible reason causing the "does not exist" issue: The image path within the JSON file may not match the actual path of the folder.

For example, consider these two different paths:

Actual folder path:
> DF40/deepfacelab/deepfacelab/fake

Expected path in JSON:
> DF40/deepfacelab/fake


If these do not match exactly, the program may fail to locate the image, even if it physically exists.

Make sure that the folder structure inside the JSON file exactly matches the real folder structure on your system.

Hope this helps! 🚀 Let me know if you need further clarification.

**Comment by Kuznetspa** [comment]
> Hi [@Kuznetspa](https://github.com/Kuznetspa), it seems like this is a new issue. However, I still appreciate your question!

I've found that in the `load_rgb` function in [abstract_dataset.py of DeepfakeBench](https://github.com/SCLBD/DeepfakeBench/blob/main/training/dataset/abstract_dataset.py) dataset root is added to the file path.

<img width="645" alt="Image" src="https://github.com/user-attachments/assets/91900167-b7b3-4dcf-a064-276465304dd5" />

But in DF40 it isn't.

<img width="617" alt="Image" src="https://github.com/user-attachments/assets/c632ccc1-4152-4127-b9d0-9a471ee426e7" />

So we should add 

```if not self.lmdb:
            if not file_path[0] == '.':
                file_path =  f'{self.config["dataset_root_rgb"]}/'+file_path
            assert os.path.exists(file_path), f"{file_path} does not exist"
            img = cv2.imread(file_path)
```

Now it works.
